# Generated by Django 4.0.5 on 2022-06-28 07:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=160, populate_from='title')),
                ('area', models.BigIntegerField(verbose_name='area')),
                ('population', models.BigIntegerField(verbose_name='population')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utimestamp', models.DateTimeField(auto_now=True)),
                ('track', models.TextField(blank=True, editable=False)),
                ('utrack', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Continent',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('local', models.CharField(max_length=50, verbose_name='local')),
                ('code', models.IntegerField(verbose_name='code')),
                ('code2', models.CharField(max_length=2, verbose_name='code2')),
                ('code3', models.CharField(max_length=3, verbose_name='code3')),
                ('capital', models.CharField(max_length=50, verbose_name='capital')),
                ('gdp', models.BigIntegerField(verbose_name='gdp')),
                ('area', models.BigIntegerField(verbose_name='area')),
                ('population', models.BigIntegerField(verbose_name='population')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('track', models.TextField(blank=True, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geolocation.continent', verbose_name='continent')),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('pattern', models.CharField(choices=[('LTR', 'Left to Right'), ('RTL', 'Right to left'), ('TTB', 'Top to Bottom'), ('BTT', 'Bottom to Top')], default='LTR', max_length=10, verbose_name='pattern')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utimestamp', models.DateTimeField(auto_now=True)),
                ('track', models.TextField(blank=True, editable=False)),
                ('utrack', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Language',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=160, populate_from='title')),
                ('capital', models.CharField(max_length=100, verbose_name='capital')),
                ('local', models.CharField(max_length=100, null=True, verbose_name='local')),
                ('area', models.BigIntegerField(verbose_name='area')),
                ('population', models.BigIntegerField(verbose_name='population')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utimestamp', models.DateTimeField(auto_now=True)),
                ('track', models.TextField(blank=True, editable=False)),
                ('utrack', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.country', verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'State',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=160, populate_from='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utimestamp', models.DateTimeField(auto_now=True)),
                ('track', models.TextField(blank=True, editable=False)),
                ('utrack', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('state', models.ManyToManyField(to='geolocation.state', verbose_name='state')),
            ],
            options={
                'verbose_name_plural': 'Region',
            },
        ),
    ]
