# Generated by Django 4.0.5 on 2022-06-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStock',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Low Stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.product',),
        ),
        migrations.CreateModel(
            name='OutOfStock',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Out of Stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.product',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.order',),
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Stock In',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.product',),
        ),
    ]
